import { describe, expect, it, vi } from "vitest";
import type { ExtensionContext, IrcExtensionConfig } from "@yoplai/shared";
import { IrcRouter } from "./router.js";

const config: IrcExtensionConfig = { host: "localhost", port: 6667, tls: false, nick: "yoplai", channels: { "#team": { agent: "main", mode: "mention-only" } }, dm: { enabled: true, agent: "main", allowFrom: ["alice"], debounceMs: 1 }, historyLimit: 3, maxA2ATurns: 2, humanNicks: ["alice"] };
function setup(payloads = [{ text: "**ok**" }], routerConfig: IrcExtensionConfig = config) { const runAgent = vi.fn().mockResolvedValue({ payloads, meta: { durationMs: 0, sessionId: "x" } }); const ctx = { getAgent: () => ({ id: "main", workspace: ".", extensions: { irc: { enabled: true } } }), getAgents: () => [], isAgentActive: vi.fn(() => true), runAgent } as unknown as ExtensionContext; const send = vi.fn(); return { ctx, router: new IrcRouter(ctx, routerConfig, { send, nick: "yoplai" }), runAgent, send }; }
const message = (prefix: string, target: string, trailing: string) => ({ prefix, command: "PRIVMSG", params: [target], trailing });
describe("IRC router", () => {
  it("acks accepted channel messages before invoking the agent", () => { const { router, runAgent, send } = setup([]); router.handle(message("bob!u@h", "#team", "yoplai: answer")); expect(send).toHaveBeenCalledWith("#team", "👀"); expect(send.mock.invocationCallOrder[0]).toBeLessThan(runAgent.mock.invocationCallOrder[0]); });
  it("acks reply-all channel messages without requiring a mention", () => { const { router, runAgent, send } = setup([], { ...config, channels: { "#team": { agent: "main", mode: "reply-all" } } }); router.handle(message("bob!u@h", "#team", "answer")); expect(send).toHaveBeenCalledWith("#team", "👀"); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "answer" })); });
  it("does not ack ignored, unaddressed, disallowed, or loop-guarded messages", () => { const { ctx, router, runAgent, send } = setup([]); router.handle(message("bob!u@h", "#team", "unaddressed")); router.handle(message("mallory!u@h", "yoplai", "disallowed")); router.handle(message("yoplai!u@h", "#team", "yoplai: loop")); const guardedSend = vi.fn(); const guarded = new IrcRouter(ctx, { ...config, maxA2ATurns: 0, humanNicks: [] }, { send: guardedSend, nick: "yoplai" }); const warn = vi.spyOn(console, "warn").mockImplementation(() => {}); try { guarded.handle(message("bob!u@h", "#team", "yoplai: capped")); } finally { warn.mockRestore(); } expect(runAgent).not.toHaveBeenCalled(); expect(send).not.toHaveBeenCalled(); expect(guardedSend).not.toHaveBeenCalled(); });
  it("acks a debounced DM once when its coalesced run dispatches", async () => { vi.useFakeTimers(); try { const { router, runAgent, send } = setup([]); router.handle(message("alice!u@h", "yoplai", "one")); router.handle(message("alice!u@h", "yoplai", "two")); expect(send).not.toHaveBeenCalled(); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(1); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "one\ntwo", sessionKey: "irc:alice" })); expect(send.mock.calls.filter(([, text]) => text === "👀")).toEqual([["alice", "👀"]]); } finally { vi.useRealTimers(); } });
  it("uses ambient channel context and replies to nick-addressed messages", async () => { const { router, runAgent, send } = setup(); router.handle(message("bob!u@h", "#team", "unaddressed context")); router.handle(message("bob!u@h", "#team", "yoplai: answer")); await new Promise((resolve) => setTimeout(resolve, 10)); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "answer", sessionKey: "irc:#team", context: expect.objectContaining({ kind: "irc" }) })); await new Promise((resolve) => setTimeout(resolve, 450)); expect(send).toHaveBeenCalledWith("#team", "ok"); });
  it("accepts the exact dedicated owner without legacy extension opt-in", async () => { const runAgent = vi.fn().mockResolvedValue({ payloads: [], meta: {} }); const ctx = { getAgent: () => ({ id: "main", workspace: "." }), isAgentActive: () => true, runAgent } as unknown as ExtensionContext; const router = new IrcRouter(ctx, config, { send: vi.fn(), nick: "yoplai" }, "main"); router.handle(message("bob!u@h", "#team", "yoplai: owned")); await new Promise((resolve) => setTimeout(resolve, 10)); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ agentId: "main", message: "owned" })); });
  it("requires legacy opt-in for agents other than the dedicated owner", () => { const runAgent = vi.fn(); const ctx = { getAgent: (id: string) => ({ id, workspace: "." }), isAgentActive: () => true, runAgent } as unknown as ExtensionContext; const shared = new IrcRouter(ctx, config, { send: vi.fn(), nick: "yoplai" }); const otherOwner = new IrcRouter(ctx, config, { send: vi.fn(), nick: "yoplai" }, "other"); shared.handle(message("bob!u@h", "#team", "yoplai: shared")); otherOwner.handle(message("bob!u@h", "#team", "yoplai: not owned")); expect(runAgent).not.toHaveBeenCalled(); });
  it("requires explicit DM enablement and discards debounced work on stop", async () => { vi.useFakeTimers(); try { const { ctx, router, runAgent } = setup(); const disabled = new IrcRouter(ctx, { ...config, dm: undefined }, { send: vi.fn(), nick: "yoplai" }); disabled.handle(message("alice!u@h", "yoplai", "nope")); router.handle(message("alice!u@h", "yoplai", "later")); router.stop(); await vi.advanceTimersByTimeAsync(1); expect(runAgent).not.toHaveBeenCalled(); } finally { vi.useRealTimers(); } });
  it("batches a mention-only channel burst from the same sender into one run", async () => { vi.useFakeTimers(); try { const { ctx, runAgent } = setup(); const router = new IrcRouter(ctx, { ...config, debounceMs: 1 }, { send: vi.fn(), nick: "yoplai" }); router.handle(message("bob!u@h", "#team", "yoplai: start")); router.handle(message("bob!u@h", "#team", "follow one")); router.handle(message("bob!u@h", "#team", "follow two")); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(1); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "start\nfollow one\nfollow two", sessionKey: "irc:#team" })); } finally { vi.useRealTimers(); } });
  it("does not merge concurrent senders in the same channel", async () => { vi.useFakeTimers(); try { const { ctx, runAgent } = setup(); const router = new IrcRouter(ctx, { ...config, debounceMs: 1 }, { send: vi.fn(), nick: "yoplai" }); router.handle(message("bob!u@h", "#team", "yoplai: from bob")); router.handle(message("carol!u@h", "#team", "yoplai: from carol")); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(2); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "from bob" })); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "from carol" })); } finally { vi.useRealTimers(); } });
  it("discards a pending batch if its agent becomes inactive", async () => { vi.useFakeTimers(); try { const { ctx, runAgent, send } = setup(); const isAgentActive = vi.mocked(ctx.isAgentActive); isAgentActive.mockReturnValueOnce(true).mockReturnValue(false); const router = new IrcRouter(ctx, { ...config, debounceMs: 1 }, { send, nick: "yoplai" }); router.handle(message("bob!u@h", "#team", "yoplai: later")); await vi.advanceTimersByTimeAsync(1); expect(runAgent).not.toHaveBeenCalled(); expect(send).not.toHaveBeenCalled(); } finally { vi.useRealTimers(); } });
  it("counts a debounced channel batch as one A2A turn", async () => { vi.useFakeTimers(); const warn = vi.spyOn(console, "warn").mockImplementation(() => {}); try { const { ctx, runAgent } = setup(); const router = new IrcRouter(ctx, { ...config, debounceMs: 1, maxA2ATurns: 1 }, { send: vi.fn(), nick: "yoplai" }); router.handle(message("bob!u@h", "#team", "yoplai: first")); router.handle(message("bob!u@h", "#team", "yoplai: second")); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(1); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "first\nsecond" })); router.handle(message("bob!u@h", "#team", "yoplai: capped")); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(1); } finally { warn.mockRestore(); vi.useRealTimers(); } });
  it("runs channel messages immediately without top-level debounceMs", async () => { const { router, runAgent } = setup(); router.handle(message("bob!u@h", "#team", "yoplai: answer")); await new Promise((resolve) => setTimeout(resolve, 10)); expect(runAgent).toHaveBeenCalledTimes(1); });
  it("batches a reply-all channel burst with debounceMs", async () => { vi.useFakeTimers(); try { const { ctx, runAgent } = setup(); const replyAll = { ...config, channels: { "#team": { agent: "main", mode: "reply-all" as const } }, debounceMs: 1 }; const router = new IrcRouter(ctx, replyAll, { send: vi.fn(), nick: "yoplai" }); router.handle(message("bob!u@h", "#team", "one")); router.handle(message("bob!u@h", "#team", "two")); await vi.advanceTimersByTimeAsync(1); expect(runAgent).toHaveBeenCalledTimes(1); expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({ message: "one\ntwo" })); } finally { vi.useRealTimers(); } });
});
